jtac radio key and weyland-yutani readio key
CM-14/CM-14 pull request #2043
Opened 2024-04-28 18:08 UTC by DangerRevolution

## About the PR

Fixes #1937, Fixes #1868, Fixes #1790, Fixes #1678, Fixes #1619, Fixes #1508, Fixes #1437

**Changelog**

:cl: DangerRevolution
- add: Added JTAC Radio Key
- add: Add Weyland-Yutani radio key

2024-04-28 18:08 UTC, DangerRevolution commented
just as a side comment, it looks like CM13 removed the Tactics Key, can't find much mention of it on the github aside from changelog entries.

2024-04-28 23:44 UTC, QuietlyWhisper requested changes
Wrong ID in a few places is causing tests to fail

2024-04-28 23:44 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Entities/Structures/Machines/colmartech_vendors.yml
> +      - id: CMJTACRadioEncryptionKey
```suggestion
      - id: CMEncryptionKeyJTAC
```

2024-04-28 23:44 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Entities/Structures/Machines/colmartech_vendors.yml
> +      - id: CMJTACRadioEncryptionKey
```suggestion
      - id: CMEncryptionKeyJTAC
```

2024-04-28 23:44 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Entities/Structures/Machines/colmartech_vendors.yml
> +      - id: CMJTACRadioEncryptionKey
```suggestion
      - id: CMEncryptionKeyJTAC
```

2024-04-28 23:44 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Entities/Structures/Machines/colmartech_vendors.yml
> +      - id: CMJTACRadioEncryptionKey
```suggestion
      - id: CMEncryptionKeyJTAC
```

2024-04-28 23:44 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Entities/Structures/Machines/colmartech_vendors.yml
> +      - id: CMJTACRadioEncryptionKey
```suggestion
      - id: CMEncryptionKeyJTAC
```

2024-04-28 23:44 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Entities/Structures/Machines/colmartech_vendors.yml
> +      - id: CMJTACRadioEncryptionKey
```suggestion
      - id: CMEncryptionKeyJTAC
```

2024-04-29 07:31 UTC, DangerRevolution commented
> Wrong ID in a few places is causing tests to fail

thank you, must've got confused at some point and was writing the wrong ID lol

2024-04-29 08:17 UTC, DangerRevolution commented
test fail doesn't seem related to me

2024-04-30 06:35 UTC, QuietlyWhisper approved these changes

2024-04-30 06:37 UTC, merged