add the coif
CM-14/CM-14 pull request #2046
Opened 2024-04-29 16:48 UTC by DangerRevolution

## About the PR
title. this needs some extra race-based sprites to be made

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame

**Changelog**

:cl: DangerRevolution
- add: Added the Coif

2024-04-29 16:51 UTC, DangerRevolution commented
gonna leave this as a draft because i don't really feel like spriting wider masks for Lizards & Vox right now.

2024-05-02 11:14 UTC, DangerRevolution commented
okay, well, i've done the Reptile sprite but I *cannot* for the *life* of me get this thing to show up for Reptiles. Gonna test it more soon.

2024-05-07 05:44 UTC, QuietlyWhisper requested changes
Just one last thing before merge

2024-05-07 05:44 UTC, QuietlyWhisper commented on Resources/Textures/_CM14/Objects/Clothing/Mask/coif.rsi/meta.json
> +  "copyright": "Taken from CM-SS13 at https://github.com/cmss13-devs/cmss13/blob/master/icons/mob/humans/onmob/mask.dmi",
You just need to add onto this your two new sprites and that you modified them (they're considered your modified sprites)

2024-05-11 05:49 UTC, QuietlyWhisper approved these changes

2024-05-11 05:49 UTC, merged