Removed Stairs Decals (Depreceated) Portet CM Medical Decals
CM-14/CM-14 pull request #215
Opened 2023-11-04 15:06 UTC by MaloTV

## About the PR

New Decals

## Why / Balance
Removed Depreceated Decals due to not being usefull and taking up alot of the decal Pannel
Added Original Cm Medical decals for mapping purposes

## Media
![image](https://github.com/CM-14/CM-14/assets/70515562/dcbe5440-e07c-4888-9bdb-75afb52c1a21)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
New Decals

**Changelog**

:cl:Malo
- add: Added Original CM Medical Decals
- remove: Depreceated Decals

2023-11-04 15:10 UTC, UbaserB commented
why do i like these decals a lot

2023-11-04 15:13 UTC, QuietlyWhisper requested changes
These should be in Textures/.CM14/Decals/Medical
and Prototypes/.CM14/Decals/Medical

All images should be named `name_name.png` for consistency.

2023-11-04 15:13 UTC, QuietlyWhisper commented on Resources/Textures/Decals/medical_decals.rsi/meta.json
> +  "copyright": null,
Missing contents here.

2023-11-04 15:14 UTC, QuietlyWhisper commented on Resources/Textures/Decals/medical_decals.rsi/meta.json
> +  "copyright": null,
RSI Editor will autofill this if you paste the url of the github link you downloaded the .dmi at.

2023-11-04 15:15 UTC, QuietlyWhisper commented on Resources/Textures/Decals/medical_decals.rsi/meta.json
> +  "copyright": null,
https://discord.com/channels/1168210010233376858/1168210011823026271/1169807706123685968

2023-11-05 03:31 UTC, DrSmugleaf commented
Thanks for the PR, I updated it to work with the new way that we can hide non-cm decals from the spawn menu in [this commit](https://github.com/CM-14/CM-14/commit/82449885145b5666226c7d9aea30795216ebc9bc) so that we don't need to delete any decals from upstream, this is what it looks like in-game:

![image](https://github.com/CM-14/CM-14/assets/10968691/7d3b2cf3-3710-4a3d-987a-c2fddfe3b053)

2023-11-05 03:31 UTC, merged