Added M79 prototype, and sound effect.
CM-14/CM-14 pull request #2470
Opened 2024-06-14 10:23 UTC by amo020

Added the M79 prototype
Added the M79 sound effect imported from CM13

tweaked the spritwork are sling and backpack were inverted.

## Media

https://github.com/CM-14/CM-14/assets/167775671/3ee24268-f9a7-41a2-a132-ecdee43e9a19

**Changelog**

:cl:
- add: Added the M79 grenade launcher prototype

2024-06-14 10:23 UTC, amo020 commented
linked to #879

2024-06-15 04:38 UTC, QuietlyWhisper requested changes

2024-06-15 04:38 UTC, QuietlyWhisper commented on Resources/Audio/_CM14/Weapons/Guns/Cock/m79_break_open.ogg
This file is missing an attributions.yml source

2024-06-15 07:36 UTC, amo020 commented on Resources/Audio/_CM14/Weapons/Guns/Cock/m79_break_open.ogg
a yes. and i did not used it also because there is no 'emptyGun' state

2024-06-15 22:13 UTC, QuietlyWhisper approved these changes
Looks good thanks

2024-06-15 22:13 UTC, merged