Holocards and related functionality
CM-14/CM-14 pull request #2544
Opened 2024-06-19 17:25 UTC by blueDev2

## About the PR

Added holocards, small icons that can be applied to people by medics doing triage

## Technical details

The Holocard status component is a networked component that tells the client which icon to show when a viewer is using a medical hud
The Holocard scanner component is a component attached to medical huds that allow medically trained individuals to examine a person and change the holocard on them
The health analyzer BUI has been changed to include a holocard change button and a holocard description. The holocard change button is disabed for non-medically trained individuals

## Media

https://github.com/CM-14/CM-14/assets/89804215/a6f3aae8-e7ad-4eb9-a0d1-8e5c58b85cca

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: blueDev2
- add: Added Holocards

2024-06-19 23:21 UTC, QuietlyWhisper requested changes
Basic review for now.

Can you also add a space between the holocard change button and the description?

2024-06-19 23:47 UTC, blueDev2 commented on Resources/Prototypes/_CM14/Entities/Mobs/Species/base.yml
> +        interactionRange: 0
It's needed, else the health hud does properly work when changing holocards.

2024-06-19 23:48 UTC, blueDev2 commented on Resources/Textures/_CM14/Interface/VerbIcons/ambulance.svg
I literally made it myself.
I looked at a specific icon when making it but it really does not look that similar.

2024-06-19 23:50 UTC, blueDev2 commented on Resources/Textures/_CM14/Interface/health_hud_holocard.rsi/meta.json
> +  "copyright": "Taken from cmss13 at https://github.com/cmss13-devs/cmss13/blob/a68173bdb50716996547edcbcfea5b8cc18745b3/icons/mob/hud/hud.dmi",
Yeah I just copied the meta file, I'll credit myself but um, should I just put it under my name or make a link to the applicable commit?

2024-06-20 01:44 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Entities/Mobs/Species/base.yml
> +        interactionRange: 0
I asked smug to look into it just in case but dont worry about this too much

2024-06-20 01:47 UTC, QuietlyWhisper commented
> Yeah I just copied the meta file, I'll credit myself but um, should I just put it under my name or make a link to the applicable commit?

Yeah you can just use yourself as the source, link is not needed. Also applies for the two other images you made. You also get full credit for these images when someone uses our code to make a new server! That's why all assets need the copyrights text

2024-06-20 01:53 UTC, blueDev2 commented
![image](https://github.com/CM-14/CM-14/assets/89804215/76b706aa-5456-41eb-981d-e741f86c1ad3)
Added spacing

2024-06-20 01:55 UTC, blueDev2 commented
> > Yeah I just copied the meta file, I'll credit myself but um, should I just put it under my name or make a link to the applicable commit?
> 
> Yeah you can just use yourself as the source, link is not needed. Also applies for the two other images you made. You also get full credit for these images when someone uses our code to make a new server, that's why all assets need the copyrights text (We also cannot use assets with no license)

Sorry, 2 other images? I think I only made 2 images, the ambulance and the holocard icons.

2024-06-20 02:10 UTC, blueDev2 commented
Also, is there any way for me to get the contributor role on the discord?

2024-06-20 02:14 UTC, QuietlyWhisper commented
> Sorry, 2 other images? I think I only made 2 images, the ambulance and the holocard icons.

I mean those yes sorry for confusion.

> Also, is there any way for me to get the contributor role on the discord?
Ping in general, smug will review the ui code when she gets the time.

2024-06-21 03:29 UTC, DrSmugleaf approved these changes
Thanks for the PR!

2024-06-21 03:29 UTC, merged