Standart walls
CM-14/CM-14 pull request #587
Opened 2023-11-15 19:59 UTC by Tunguso4ka

## About the PR

Adds standart wall, reinforced wall, heavy reinforced wall and girder.

## Why / Balance

Resolves #261

## Media

![image_2023-11-15_21-28-28](https://github.com/CM-14/CM-14/assets/71643624/8fb8f4f4-a6c9-400b-9aad-5015d1d73312)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2023-11-15 20:01 UTC, Tunguso4ka commented
i will not do windows. No.

2023-11-16 09:59 UTC, DrSmugleaf requested changes

2023-11-16 09:59 UTC, DrSmugleaf commented on Resources/Prototypes/_CM14/Entities/Structures/Walls/girder.yml
> +  parent: Girder
This should parent CMEntityBase as well so we can categorize them later between cm and non-cm entities.
```suggestion
  parent: [Girder, CMEntityBase]
```

2023-11-16 09:59 UTC, DrSmugleaf commented on Resources/Prototypes/_CM14/Entities/Structures/Walls/walls.yml
> +  parent: BaseWall
Same here, though it would be better to first create a CMBaseWall that all of these walls inherit instead.

2023-11-16 10:04 UTC, DrSmugleaf requested changes

2023-11-16 10:04 UTC, DrSmugleaf commented on Resources/Textures/_CM14/Structures/Walls/girder.rsi/meta.json
> +  "copyright": "Taken from cmss13 at commit https://github.com/cmss13-devs/cmss13/commit/f74929c306a5d2ec5832abcdc695aea1b0786664",
This should be a link to the actual file at the given commit, not just the commit, if you copy pasted the github .dmi link into the latest version of RSIEdit, it should do that for you automatically.

I can't actually find the girder in that commit though, are you sure it comes from there?

2023-11-16 10:04 UTC, DrSmugleaf commented on Resources/Textures/_CM14/Structures/Walls/metal.rsi/meta.json
> +  "copyright": "Taken from cmss13 at commit https://github.com/cmss13-devs/cmss13/commit/f74929c306a5d2ec5832abcdc695aea1b0786664",
Same here
```suggestion
  "copyright": "Taken from cmss13 at https://github.com/cmss13-devs/cmss13/blob/f74929c306a5d2ec5832abcdc695aea1b0786664/icons/turf/walls/walls.dmi",
```

2023-11-16 10:04 UTC, DrSmugleaf commented on Resources/Textures/_CM14/Structures/Walls/rwall.rsi/meta.json
> +  "copyright": "Taken from cmss13 at commit https://github.com/cmss13-devs/cmss13/commit/f74929c306a5d2ec5832abcdc695aea1b0786664",
Same here
```suggestion
  "copyright": "Taken from cmss13 at https://github.com/cmss13-devs/cmss13/blob/f74929c306a5d2ec5832abcdc695aea1b0786664/icons/turf/walls/walls.dmi",
```

2023-11-16 11:42 UTC, DrSmugleaf approved these changes

2023-11-16 11:47 UTC, DrSmugleaf reviewed
There is one test issue with the girder's price being incorrect when deconstructed:
```
CMGirderReinforced increases in price after being destroyed
  Expected: less than or equal to 10.0d
  But was:  33.0d
```

It might matter once the cargo elevator is added

2023-11-16 12:05 UTC, Tunguso4ka commented
> There is one test issue with the girder's price being incorrect when deconstructed:

fixed.

2023-11-16 12:14 UTC, DrSmugleaf reviewed
Ok apparently that test doesn't give you the full list of wrongly priced entities so you might need to run it multiple times, I can fix that upstream tomorrow

```
  Failed NoMaterialArbitrage [3 s]
  Error Message:
     CMWallReinforced increases in price after being deconstructed
  Expected: less than or equal to 75.0d
  But was:  122.00000000000001d
```

2023-11-16 12:43 UTC, Tunguso4ka commented
yay, all green.

2023-11-16 15:50 UTC, Tunguso4ka commented
ready to review.

2023-11-16 17:48 UTC, DrSmugleaf approved these changes
Thanks for the PR, I'll make an upstream change later to make the test that verifies prices show all wrongly priced entities at once so we don't have the same problem again

2023-11-16 17:49 UTC, merged