Requisition department
CM-14/CM-14 pull request #592
Opened 2023-11-16 20:17 UTC by Tunguso4ka

## About the PR
Adds Requisition department, three new roles for it: Quartermaster, Cargo Technician and Mess Technician and clothes for them.

## Why / Balance
Resolves #170, resolves #172, resolves #173, resolves #174, resolves #176, resolves #177, resolves #178, resolves #180, resolves #181

## Media

![image_2023-11-16_22-50-55](https://github.com/CM-14/CM-14/assets/71643624/e7d01ff7-6b47-40ec-a56c-d6db3d4f531e)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Tunguso4ka
- added: Requisition department has been added to the game.

2023-11-16 20:25 UTC, Tunguso4ka commented
Ready to review.

2023-11-16 21:36 UTC, Tunguso4ka commented
wait. why the fuck wo uniform changed. oohh

2023-11-16 21:42 UTC, Tunguso4ka commented
Ready to review.

2023-11-16 21:46 UTC, Tunguso4ka commented
test problem dont really looks like mine problem.

2023-11-17 01:52 UTC, DrSmugleaf requested changes

2023-11-17 01:52 UTC, DrSmugleaf commented on Resources/Textures/_CM14/Objects/Clothing/Head/Hats/cargocap.rsi/meta.json
> +  "copyright": "Taken from cmss13 at commit https://github.com/cmss13-devs/cmss13/commit/05eaa3484b1a35aa759300bcfc8f0119f009daae",
```suggestion
  "copyright": "Taken from cmss13 at https://github.com/cmss13-devs/cmss13/blob/05eaa3484b1a35aa759300bcfc8f0119f009daae/icons/obj/items/clothing/cm_hats.dmi and https://github.com/cmss13-devs/cmss13/blob/05eaa3484b1a35aa759300bcfc8f0119f009daae/icons/mob/humans/onmob/head_1.dmi",
```

2023-11-17 07:11 UTC, Tunguso4ka commented
i really dont know why it throwing DebugAssertException on SpawnAndDeleteAllEntitiesInTheSameSpot.

2023-11-17 07:52 UTC, Tunguso4ka commented
where my debug assert exception.

2023-11-17 08:03 UTC, DrSmugleaf commented
> where my debug assert exception.

I reran tests to see if it was a random fail, looks good, thank you for the PR

2023-11-17 08:03 UTC, DrSmugleaf approved these changes

2023-11-17 08:03 UTC, merged