ComTech Barricades
CM-14/CM-14 pull request #674
Opened 2023-11-25 07:21 UTC by thymol-blue

## About the PR

This is my first PR in SS14 and also my first time doing anything with Github! Apologies in advance if I miss anything. I am leaving this as a draft because I need some help from smarter people (see bottom).

Added:
1. Basic Barricades.
2. Upgrades for Basic Barricades.
     2.1. anti-Biohazard Upgrade.
     2.2. Blast Resistance Upgrade.
     2.3. Brute Resistance Upgrade.
     2.4. Damage Modifiers for aforementioned upgrades.
     2.5. Placeholder for radial menu is added steel/metal rods/plasteel to choose upgrade.
3. Sandbag sprite (needs entrenching tool design).
4. Damaged sprites for all of the aforementioned barricades.
5. Plasteel and Metal foldable barriers (doors!).
6. Turnstile sprites (for now, they are just fences until I figure out how to make one-way doors).
7. Crafting graphs and recipes in construction menu for aforementioned items.

## Why / Balance

- Resolves #670 
- Moves it towards resolving #485 and #486 
- Love CM13 but can't stand BYOND after playing SS14.  Super excited for this first playtest.

## Technical details

- Used DamageVisuals component to make sprites change based on health (like cracked windows!)
- Sound effects are from fences and grills.

## Media

Damaged Barricades
![image](https://github.com/CM-14/CM-14/assets/53154853/7ae8f86b-f8cf-43f8-8114-adabb6c0c0ec)

Rotated Barricades
![image](https://github.com/CM-14/CM-14/assets/53154853/3838ddf5-cd05-481d-a4a1-d897d761445a)

Constructing and Destroying Barricades (and blowing them up!)

https://youtu.be/gV34GDBdEDQ

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None... I think?
**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Added barricades, barricade upgrades, barricade doors, damaged sprites, and turnstiles. Also added ways to make them!

## Todo-list (I need help!)

- [X] Barricades
- [ ] Barbed Wire and Barbed Wire layer over barricades
    - [ ] Barbed Wire damage on attack
- [ ] Damaged indicators for plasteel and metal doors
- [ ] Portable/Foldable wall
- [ ] Radial Menu/Better way of upgrading barricades
- [ ] Sandbag entrenching tool and construction
- [ ] One-way Turnstile Doors
- [ ] Masking problems.
    - [ ] Barricades. Walking in front of a bottom-facing barricade causes you to be in-front of it.
    - [ ] Barricade Doors. Walking in front of a top-facing barricade causes you to be behind it (what?!),
- [ ] Balance Input
    - [ ] Crafting Cost
    - [ ] Barricade health
    - [ ] Barricade DamageModifers
- [ ] File organization. It is my first time coding and I worried my organization might not be great/up-to-par with other PRs.

2023-11-25 07:40 UTC, Tunguso4ka commented
as i remember PR that added radial menu support to the SS14 was closed. So you probably should use the menu that Smug used for xeno constructions/evolutions.

2023-11-25 08:16 UTC, QuietlyWhisper requested changes
CM14 content and files should be seperated into their respective _CM14 folder at 
`resources/prototypes/_CM14`/etc
And
`resources/textures/_CM14`/etc
It prevents conflicts from upstream when the files are updated on upstream 👍 

Also if CM13 sounds are different let us know bc theyre easy to port

2023-11-25 08:36 UTC, Tunguso4ka commented
*_CM14, with underscore

2023-11-25 21:03 UTC, thymol-blue commented on Content.Server/KillTracking/KillTrackingSystem.cs
I have no idea why this keeps getting removed and added. I have unstaged it every commit and yet here it is. It is adding and remove the same thing so... is it fine?

2023-11-27 06:29 UTC, QuietlyWhisper submitted a review, later dismissed

2023-11-27 06:29 UTC, QuietlyWhisper commented on Resources/Audio/_CM14/Structures/metalhit.ogg
Needs attribution
Look at any attribution.yml for format
goes in the same folder as the sound file

2023-11-27 06:29 UTC, QuietlyWhisper commented on Content.Server/KillTracking/KillTrackingSystem.cs
fixed it for you

2023-11-27 06:50 UTC, QuietlyWhisper requested changes

2023-11-27 06:50 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Recipes/Construction/Graphs/structures/barricade_plasteel_door.yml
> +      - material: Plasteel
YML linter is saying Plasteel isn't the correct entity ID, it should be SheetPlasteel
```suggestion
      - material: SheetPlasteel
```

2023-11-27 06:50 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Recipes/Construction/Graphs/structures/barricade_plasteel_door.yml
> +          prototype: Plasteel
```suggestion
          prototype: SheetPlasteel
```

2023-11-27 08:26 UTC, JoeHammad1844 commented
can you place multiple barricades on the same tile like CM13?

2023-11-27 08:34 UTC, QuietlyWhisper commented
> can you place multiple barricades on the same tile like CM13?

didn't think about that but it would be very easy, just make them directional window style walls
though we'd need to fix this
![image](https://github.com/CM-14/CM-14/assets/121047731/88c98e78-e710-41a0-8c45-c65cfe33907c)

2023-11-27 09:00 UTC, JoeHammad1844 commented
![image](https://github.com/CM-14/CM-14/assets/130668733/44f89058-c0e9-4637-a7d0-41fb16fc6450)

2023-11-27 09:05 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Recipes/Construction/Graphs/structures/barricade_plasteel_door.yml
> +          prototype: Plasteel
```suggestion
          prototype: SheetPlasteel1
```

2023-11-27 09:06 UTC, QuietlyWhisper commented
> having barricades in the right direction is important for SS13 CM for two reasons
> 
> 1. grenades can only go one way through barricades
> 2. aesthetics
> 3. xenos can burrow through walls and being unable to patch that up is cringe

yeah this seems to be something we need to fix upstream and not just for cm14

2023-11-27 17:24 UTC, QuietlyWhisper commented
@DrSmugleaf We need this for mapping, can you look into making sure these are directional window style walls? I think this upgrade system works for now and we only need the ability to close it with an empty hand as a marine but not xeno

We can probably look into making the rest of the mechanics later

2023-11-28 03:11 UTC, DrSmugleaf approved these changes
In the future this will need a new system for turnstiles allowing movement through one direction only, and fixing how barricade sprites are drawn so that the bottom one always draws on top of the side ones and on top of players that are behind them, but for now this is good enough, thanks for the PR!

2023-11-28 03:35 UTC, thymol-blue commented
Thanks for the edits, I didn't want to name it Barricades to conflict with the SS14 barricades but since it's in another folder it should be fine.

Also general rule of thumb for future commits, no underscores and CM at the front for naming convention?

2023-11-28 03:43 UTC, DrSmugleaf commented
> Thanks for the edits, I didn't want to name it Barricades to conflict with the SS14 barricades but since it's in another folder it should be fine.
> 
> Also general rule of thumb for future commits, no underscores and CM at the front for naming convention?

It depends on what you are naming, [this should have the up to date conventions](https://docs.spacestation14.com/en/general-development/codebase-info/conventions.html)
But in general, prototype ids should be `PascalCase` (id: CMBarricadeMetal), no underscores. We still haven't made a decision on whether or not every cm-specific id should be prefixed with CM or not, but its most important when there is a conflict with an id upstream.
Construction node names should be `camelCase` (nodeMetal), no underscores.
RSI states should be `snake_case` (brute_upgrade.png), though note that this doesn't apply to DamageOverlay_4.png as the code enforces a different naming convention.
.rsi folders should be `snake_case.rsi` (brute_barricade_cracks.rsi), and folders containing multiple .rsi folders should be `PascalCase` (Barricades, TrashDrinks)

2023-11-28 03:47 UTC, DrSmugleaf commented
For copyrights as well, any folder with sound files should have an [attributions.yml file](https://github.com/CM-14/CM-14/pull/674/commits/284971be69953ef1b87f4ed4c2c8e0d8eac57636), going to fix the one for guns in another PR now.

RSI meta.json copyright should be in the format of "Taken from cmss13 at link-to-file-with-commit-id", such as ["Taken from cmss13 at https://github.com/cmss13-devs/cmss13/blob/41109aa6eebf87892e41b61418b7b06b279d04b6/icons/obj/structures/barricades.dmi"](https://github.com/CM-14/CM-14/pull/674/commits/40c5dc0365f7160076b6710472a2bc82c33585af).
This is so that we know both which file and which commit the file came from in the future.

RSIEdit will do this for you automatically if you copy a GitHub .dmi link and paste it with CTRL+V into RSIEdit.

https://github.com/CM-14/CM-14/assets/10968691/395c3e8e-5fe9-4cdf-a0be-d7542eee7708

2023-11-28 03:49 UTC, DrSmugleaf approved these changes

2023-11-28 03:55 UTC, merged