Vending machines
CM-14/CM-14 pull request #728
Opened 2023-12-02 18:01 UTC by Tunguso4ka

## About the PR
todo:
- [ ] Add all sprites
- [ ] Fix sprite animation speeds
- [ ] Make prototypes
- [ ] Fill what can be filled

## Why / Balance
Resolves #263 

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2023-12-03 17:17 UTC, Tunguso4ka commented
Ready to review.
My opinion is that med vendors should be filled in medical PR.

2023-12-03 17:21 UTC, QuietlyWhisper requested changes

2023-12-03 17:21 UTC, QuietlyWhisper commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/.drinks_bottles.yml.swp
swap file go brrr (I don't know why these keep coming up now)

2023-12-03 17:21 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Catalog/VendingMachines/Inventories/chemistry.yml
> +  #startingInventory:
```suggestion
  #startingInventory: #todo cm14
```

2023-12-03 17:21 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Catalog/VendingMachines/Inventories/cigs.yml
> +    CigPackBlack: 50 #lucky strikes
```suggestion
    CigPackBlack: 50 #lucky strikes #todo cm14
```

2023-12-03 17:21 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Catalog/VendingMachines/Inventories/cola.yml
> +    # Souto drinks, All souto drinks, like all all. 10
```suggestion
    # TODO cm14 Souto drinks, All souto drinks, like all all. 10
```

2023-12-03 17:21 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Catalog/VendingMachines/Inventories/marine_food.yml
> +    # Prepared meal
```suggestion
    # Prepared meal todo cm14
```

2023-12-03 17:21 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Catalog/VendingMachines/Inventories/marine_med.yml
> +  #startingInventory:
```suggestion
  #startingInventory: todo cm14
```

2023-12-03 17:21 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Catalog/VendingMachines/Inventories/medical.yml
> +  #startingInventory:
```suggestion
  #startingInventory: todo cm14
```

2023-12-03 17:25 UTC, Tunguso4ka commented on Resources/Prototypes/_CM14/Entities/Structures/Machines/.vending_machines.yml.swp
oh.

2023-12-05 07:42 UTC, QuietlyWhisper approved these changes

2023-12-05 07:42 UTC, merged