Pheromones cleanup
CM-14/CM-14 pull request #763
Opened 2023-12-24 15:03 UTC by nikthechampiongr

## About the PR

Moved a bunch of constants in the XenoPheromonesSystem in their respective Pheromones Components. Also made all the pheromone components SessionSpecific. This resolves 2 outstanding TODOs on the system.

## Why / Balance

This allows pheromone effects to be modified without affecting every other xeno(should that ever be necessary), it also follows the ECS philosophy more if that matters.

Components that have info about bonuses the xenos have no longer get leaked to clients that should not know about them like marines.
## Technical details

I just moved every relevant constant to their components. For SessionSpecific it's all handled by a single function with a generic argument over the component which just checks whether the entity receiving them is a xeno.
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl no fun

2023-12-24 16:37 UTC, DrSmugleaf requested changes
Some small changes and it should be good to merge, thanks for the PR!
Might need to check if being a marine and controlling a xeno makes you get existing pheromones components or not, if not then you would need to dirty all pheromones components when someone becomes a xeno, but that can be done later.

2023-12-24 16:37 UTC, DrSmugleaf commented on Content.Shared/_CM14/Xenos/Pheromones/XenoFrenzyPheromonesComponent.cs
> +    public List<string> DamageTypes = new () { "Blunt", "Slash", "Piercing" };
This should be DamageTypePrototype, not DamageGroupPrototype (Brute is a group, Blunt/Slash/Piercing are types) 
ProtoId<DamageTypePrototype> can be used instead so you don't need to use a custom type serializer.
You might need to update some usages after this is done.

```suggestion
    [DataField]
    public List<ProtoId<DamageTypePrototype>> DamageTypes = new () { "Blunt", "Slash", "Piercing" };
```

2023-12-24 16:37 UTC, DrSmugleaf commented on Content.Shared/_CM14/Xenos/Pheromones/XenoWardingPheromonesComponent.cs
> +    public string DamageTypeTwo = "Asphyxiation";
These two should be in a list as with XenoFrenzyPheromonesComponent.

2023-12-24 17:00 UTC, nikthechampiongr commented
> Might need to check if being a marine and controlling a xeno makes you get existing pheromones components or not

I can test that but what do you mean by this? When does a marine control a xeno?

2023-12-24 17:01 UTC, nikthechampiongr commented
Oh if it's just about new xenos not getting the pheromones I can test that one second.

2023-12-24 17:05 UTC, nikthechampiongr commented
Ok actually thanks a lot for the heads up. I fucked up the function for SessionSpecific, had to use args.Player not uid. Forgot uid is for the actual entity with the component.

2023-12-24 17:39 UTC, nikthechampiongr commented
Alright so I did as much testing as I could locally, however I am not 100% certain it works perfectly. Specifically, having 2 clients connected and making one a xeno will lead to the human client knowing about the pheromone component. For some reason it won't know about the other pheromone components once the xeno starts emitting them. Putting the xeno pheromone component to some random mob will lead to the xeno client knowing about while the human does not which is how it's supposed to work. I did all the testing with View Variables.

2023-12-24 17:39 UTC, nikthechampiongr commented
> Alright so I did as much testing as I could locally, however I am not 100% certain it works perfectly. Specifically, having 2 clients connected and making one a xeno will lead to the human client knowing about the pheromone component. For some reason it won't know about the other pheromone components once the xeno starts emitting them. Putting the xeno pheromone component to some random mob will lead to the xeno client knowing about while the human does not which is how it's supposed to work. I did all the testing with View Variables.

This does also mean that a human becoming a xeno works perfectly fine.

2023-12-25 00:22 UTC, nikthechampiongr commented
Ok I will need to actually hunt down the XenoPheremonesComponent bug that makes it known to the client even when it shouldn't.

2023-12-25 00:52 UTC, nikthechampiongr commented
Nvm there is no point. It will do what it needs to do even if clients get the initial state of it.

2023-12-25 00:54 UTC, DrSmugleaf approved these changes

2023-12-25 00:55 UTC, merged