Pouches pt. 2 (now will flares)
CM-14/CM-14 pull request #980
Opened 2024-02-12 22:43 UTC by KittenColony

## About the PR
Adds functionality to many of the pouches, adds various items that goes with them

## Why / Balance
#520 

## Technical details
YAML and Sprites

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

2024-02-12 22:58 UTC, KittenColony commented
why the fuck are flares so difficult :(

2024-02-12 23:31 UTC, KittenColony commented
why the fuck am I doing this, we already have all the pouches asked for in #520, do I just need to give them fills?

2024-03-02 09:50 UTC, KittenColony commented
flare might be too bright :clueless:

2024-03-02 10:18 UTC, KittenColony commented
heads up, flares are very red and I don't know what you'd want them to be changed to

2024-03-02 10:27 UTC, QuietlyWhisper commented
these sprites should be vertical otherwise they don't fit properly in the ui

2024-03-02 10:27 UTC, QuietlyWhisper commented
![image](https://github.com/CM-14/CM-14/assets/121047731/66515b9f-4248-4d16-84b9-90348377baa1)

2024-03-02 10:27 UTC, QuietlyWhisper commented
I can probably fix it though, but I find it stupid that SS14 even needs "storage" sprites, seems like a waste of space

2024-03-02 10:31 UTC, QuietlyWhisper commented
![storage](https://github.com/CM-14/CM-14/assets/121047731/1ebde4a6-59b5-4ed4-a974-59bc63c3f7b2)
You'll need this

2024-03-02 10:32 UTC, QuietlyWhisper requested changes

2024-03-02 10:32 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Entities/Objects/Tools/flares.yml
> +    size: Tiny
```suggestion
    size: Small
    storedSprite:
      sprite: _CM14/Objects/Misc/flares.rsi
      state: storage
```

2024-03-02 10:35 UTC, QuietlyWhisper commented on Resources/Prototypes/_CM14/Entities/Objects/Tools/flares.yml
> +    size: Tiny
You also need to update the meta.json obviously

2024-03-02 10:39 UTC, QuietlyWhisper commented
Other than that everything looks fine thanks!

2024-03-02 22:22 UTC, DrSmugleaf commented
> I find it stupid that SS14 even needs "storage" sprites, seems like a waste of space

You don't need one if it is the same as the regular sprite. If it's not specified it defaults to the one in the sprite component. The only case to use one is if you want the item to use a different sprite when stored, such as when the sprite doesn't fit the boundaries in the storage.

2024-03-03 08:07 UTC, QuietlyWhisper approved these changes

2024-03-03 08:08 UTC, merged